version: "3.8"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.15"
        PHOENIX_VERSION: "1.7.7"
        NODE_VERSION: "none"

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
